SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (1, 'Ústav matematických vied PF UPJŠ Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (2, 'Ústav matematických vied, PF UPJŠ Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (3, 'Katedra matematiky FPV UKF Nitra', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (4, 'Katedra matematiky a fyziky PF KU Ružomberok', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (5, 'Katedra matematiky Stavební fakulta ČVUT Praha', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (6, 'Matematický ústav Akademie věd ČR Praha', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (7, 'Katedra matematiky FPV UMB Banská Bystrica', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (8, 'Katedra aplikovanej matematiky SjF TU Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (9, 'Katedra fyziky FPV UMB Banská Bystrica', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (10, 'Lekárska fakulta UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (11, 'Katedra fyziky FEI STU Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (12, 'Katedra teoretickej fyziky FMFI UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (13, 'Osemročné športové gymnázium Banská Bystrica', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (14, 'FPV UMB Banská Bystrica', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (15, 'Ústav lekárskej fyziky a biofyziky LF UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (16, 'Katedra základov a didaktiky fyziky FMFI UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (17, 'Ústav aplikovanej matematiky UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (18, 'Katedra základov a didaktiky matematiky FMFI UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (19, 'Katedra fyziky UHK Hradec Králové, Katedra fyzikálnych vied FPV ŽU Žilina', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (20, 'Súkromné gymnázium Prešov', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (21, 'Katedra matematiky a informatiky PF TU Trnava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (22, 'Katedra fyziky FPV UKF Nitra', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (23, 'Katedra fyziky UPHV, Trenčianska univerzita Alexandra Dubčeka Trenčín', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (24, 'Katedra fyzikálnych vied FPV ŽU Žilina', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (25, 'Katedra informatiky FPV UKF Nitra', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (26, 'Piaristické gymnázium Jozefa Braneckého Trenčín', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (27, 'FMFI UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (28, 'Pedagogická fakulta KU Ružomberok', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (29, 'Gymnázium Senica', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (30, 'Astronomický ústav SAV Tatranská Lomnica', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (31, 'Gymnázium Veľká okružná Žilina', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (32, 'ZŠ Nitra', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (33, 'Katedra matematickej analýzy a numerickej matematiky FMFI UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (34, 'Katedra algebry, geometrie a didaktiky matematiky FMFI UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (35, 'Katedra regionálnej geografie, ochrany a plánovania krajiny, Prírodovedecká fakulta UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (36, 'Katedra fyziky FEI TU Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (37, 'Gymnázium Žilina', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (38, 'Katedra humanistiky FMFI UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (39, 'Katedra aplikovanej matematiky a štatistiky FMFI UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (40, 'Department of Physics, Károly Esterházy College Eger', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (41, 'Gymnázium V. Paulínyho-Tótha Martin', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (42, 'Trenčianska univerzita Alexandra Dubčeka', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (43, 'Katedra teoretickej fyziky a didaktiky fyziky FMFI UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (44, 'Department of Technology, Juhász Gyula Teacher Training Faculty University of Szeged', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (45, 'Department of General and Environmental Physics JGYPK University of Szeged', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (46, 'Laboratoire PHASE-CNRS Strasbourg', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (47, 'Katedra fyziky Materiálovo-technologickej fakulty STU Trnava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (48, 'Matematický ústav SAV Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (49, 'Matematický ústav SAV Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (50, 'Katedra fyziky a informatiky Pedagogická fakulta Univerzita Hradec Králové', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (51, 'Katedra jadrovej fyziky a biofyziky FMFI UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (52, 'Department of Chemistry, Texas Christian University, Fort Worth, Texas, USA', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (53, 'Gymnázium, Baľka Palanka, Srbsko', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (54, 'Katedra informatiky a automatizačnej techniky, Fakulta environmentálnej a výrobnej techniky TU Zvolen', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (55, 'Katedra environmentálnej techniky, Fakulta environmentálnej a výrobnej techniky TU Zvolen', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (56, 'Gymnázium Párovská 1, Nitra', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (57, 'Přírodovědecká fakulta UJEP Ústí nad Labem', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (58, 'Katedra matematiky Strojnícka fakulta STU Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (59, 'Ústav jaderné fyziky Akademie věd, Čež', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (60, 'Instytut Matematyki Akademia Pedagogiczna, Kraków, Polska', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (61, 'Katedra matematiky SjF STU Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (62, 'Katedra matematiky  SjF STU Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (63, 'School of Education and Lifelong Learning, University of Sunderland, UK', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (64, 'Katedra matematickej analýzy a numerickej matematiky FMFI  UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (65, 'Katedra informatiky FPV UMB Banská Bystrica', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (66, 'Fakultná nemocnica, Očná klinika, Nitra', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (67, 'Eötvös Loránd Tudományegyetem, Természettudományi Kar, Anyagfizikai Tanszék, Budapest', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (68, 'Univerzita Hradec Králové, Česká republika', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (69, 'Katedra matematiky Fakulta prevádzky a ekonomiky dopravy a spojov, Žilinská univerzita v Žiline', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (70, 'Wydział Matematyczno-Przyrodniczy Uniwersytetu Rzeszowskiego, Polska', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (71, 'Katedra matematiky a didaktiky matematiky PF UK Praha, Česká republika', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (72, 'Katedra fyziky Žilinská univerzita', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (73, 'Gymnázium Galanta', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (74, 'Katedra fyziky SvF STU Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (75, 'Katedra ekonomických a finančných modelov FMFI UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (76, 'Katedra matematiky CHTF STU Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (77, 'Katedra experimentálnej fyziky PF UPJŠ Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (78, 'Katedra fyziky VA Liptovský Mikuláš', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (79, 'ŠPÚ Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (80, 'Astronomický ústav FMFI UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (81, 'Katedra geofyziky FMFI UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (82, 'Lehrstuhl für Informatik I, Aachen', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (83, 'Katedra algebry a teórie čísel MFF UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (84, 'Katedra teoretickej fyziky a geofyziky PF UPJŠ Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (85, 'Oddelenie matematickej informatiky Katedra tvárnenia kovov HF TU Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (86, 'Ústav lekárskej informatiky LF UPJŠ Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (87, 'Ústav fyzikálnych vied PF UPJŠ Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (88, 'Katedra matematiky Fakulta financií UMB Banská Bystrica', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (89, 'Katedra matematickej analýzy PF UPJŠ Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (90, 'Súkromné gymnázium Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (91, 'ZŠ Starý Tekov', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (92, 'Ekonomická univerzita Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (93, 'Gymnázium P. O. Hviezdoslava Kežmarok', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (94, 'Katedra fyziky plazmy MFF UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (95, 'Gymnázium Š. Moyzesa Ružomberok', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (96, 'FPV Žilinská univerzita', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (97, 'Katedra matematiky FPV Žilinská univerzita', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (98, 'Fieldsov Inštitút, Toronto', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (99, 'Rektorát UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (100, 'Klub fyzikov Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (101, 'OKF ÚEF SAV Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (102, 'Katedra jadrovej fyziky PF UPJŠ Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (103, 'Katedra numerických a optimalizačných metód FMFI UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (104, 'Ústav experimentálnej fyziky SAV Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (105, 'Slovenská komisia MO MFF UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (106, 'Fakulta stavební, Ústav matematiky a deskriptivní geometrie, Vysoké učení technické v Brne', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (107, 'Katedra jadrovej fyziky a techniky FEI STU Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (108, 'KMDg TU Zvolen', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (109, 'Katedra experimentálnej fyziky FMFI UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (110, 'Katedra matematiky, Univerzita Papua New Guinea', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (111, 'Gymnázium J. G. Tajovského Banská Bystrica', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (112, 'KVANT, spol. s r.o., Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (113, 'Katedra štatistiky FMFI UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (114, 'MFF KU Praha', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (115, 'New York Times', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (116, 'Odbor školstva a kultúry, Okresný úrad Trnava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (117, 'Fakulta elektrotechniky a informatiky, Slovenská technická univerzita v Bratislave', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (118, 'KVI MFF UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (119, 'Katedra geometrie MFF UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (120, 'Katedra základov a didaktiky fyziky MFF UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (121, 'Fyzikálny ústav SAV, Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (122, 'Ústav aplikovanej informatiky, automatizácie a matematiky MTF STU Trnava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (123, 'Katedra matematiky a informatiky PF UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (124, 'Katedra fyziky PF Masarykova Univerzita Brno', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (125, 'Gymnázium tř. Kpt. Jaroše Brno', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (126, 'Katedra fyziky PF TU Trnava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (127, 'Katedra fyziky, MFF UK Praha', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (128, 'Gymnázium Angely Merici, Trnava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (129, 'Katedra informatiky FEM SPU Nitra', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (130, 'Ústav technológie vzdelávania PF UKF Nitra', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (131, 'Katedra informačných sietí, Fakulta riadenia a informatiky Žilinská univerzita', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (132, 'VŠ GDF, Sládkovičovo / Katedra fyziky FPL UKF Nitra', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (133, 'Vysoká škola technická a ekonomická, České Budějovice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (134, 'Cirkevná spojená škola MARIANUM, Komárno', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (135, 'Katedra fyziky PF KU Ružomberok', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (136, 'Gymnázium, Šrobárova 1, Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (137, 'Ústav riadenia a informatizácie výrobných procesov, FBERG TU Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (138, 'mathematic- and IT teacher; 3170, Szécsény, Komjáthy Jenő street 2/b 1/1', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (139, 'Faculty of Engineering, University of Debrecen', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (140, '175 South Madison Ave, Apt. 6, Pasadena, California 91101', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (141, 'Katedra informatiky FMFI UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (142, 'University of Debrecen, Department of Geometry, H–4032 Debrecen, Egyetem tér 1', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (143, 'Pedagogická fakulta, Jihočeská univerzita v Českých Budějovicích', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (144, 'Manažér pre externú komunikáciu, Slovenské elektrárne, Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (145, 'Eszterházy Károly College, Institute of Mathematics and Computer Science, Eger, Hungary', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (146, 'University of Warwick,  Coventry United Kingdom', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (147, 'Pedagogická fakulta PU Prešov', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (148, 'Instytut Matematyki Uniwersytetu Pedagogicznego w Krakowie, Polska', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (149, 'Katedra kvantitatívnych metód a hospodárskej informatiky, Fakulta prevádzky a ekonomiky dopravy a spojov, Žilinská univerzita', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (150, 'SE spoločnosť skupiny Enel', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (151, 'Institute of Mathematics and Informatics, Eszterházy Károly College, Eger', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (152, 'Ústav teoretické fyziky a astrofyziky, Pøírodovìdecká fakulta Masarykovy univerzity, Brno', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (153, 'Infocentrum, Atómová elektráreň, Mochovce', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (154, 'KRIS FEL, Žilinská univerzita', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (155, 'riaditeľ,  Atómová elektráreň, Mochovce', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (156, 'Katedra matematických metód a operačnej analýzy, Detašované pracovisko Fakulty riadenia a informatiky, Žilinská univerzita', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (157, 'Fakulta matematiky a fyziky, Karlova univerzita, Praha', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (158, 'Katedra elektroniky, Akadémia ozbroje-ných síl generála Milana Rastislava Štefánika, Liptovský Mikuláš', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (159, 'Ústav informatiky, Prírodovedecká fakulta, Univerzita Pavla Jozefa Šafárika v Košiciach', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (160, 'Elektrotechnická fakulta, Žilinská univerzita', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (161, 'Vysoká škola pedagogická, Aarhus, Dánsko', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (162, 'Fyzikálny korešpondenčný seminár, Katedra teoretickej fyziky a didaktiky fyziky, Fakulta matematiky, fyziky a informatiky Univerzity Komenského, Mlynská dolina', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (163, 'Pedagogická fakulta, Ostravská univerzita v Ostravě', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (164, 'NÚCEM, Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (165, 'Ústav matematických vied, Univerzita Pavla Jozefa Šafárika v Košiciach', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (166, 'Matematický Ústav, Slovenská Akadémia Vied, Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (167, 'Přírodovědecká fakulta UP, Olomouc', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (168, 'FPV UMB Bansk?? Bystrica', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (169, 'Physics Education PhD Program Eötvös University, Szombathelyi Nagy Lajos Gimnázium', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (170, 'Katedra matematiky a deskriptívnej geometrie, Drevárska fakulta, Technická univerzita vo Zvolene', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (171, 'Matematicko-fyzikální fakulta, Univerzita Karlova, Praha', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (172, 'Katedra školskej didaktiky, Vysoká škola DTI, Dubnica nad Váhom', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (173, 'Ústav aplikované matematiky, Fakulta dopravní, ČVUT v Praze', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (174, 'Katolícka univerzita v Ružomberku', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (175, 'Katedra matematiky a deskriptívnej geometrie, STU v Bratislave', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (176, 'Fakulta jaderná a fyzikálně inženýrská ČVUT, Praha', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (177, 'Katedra algebry, geometrie a didaktiky matematiky, FMFI UK Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (178, 'Katedra informatiky, Akadémia ozbrojených síl generála M. R. Štefánika v Liptovskom Mikuláši', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (179, 'Fakulta prírodných vied, Banská Bystrica', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (180, 'Gymnázium, Hlinská 29, 011 80 Žilina', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (181, 'JSMF, Mlynská dolina F1, 842 48 Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (182, 'Katedra matematiky a deskriptívnej geometrie, Stavebná fakulta STU, Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (183, 'Ústav matematických vied, UPJŠ, Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (184, 'Matematický ústav SAV, Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (185, 'Matematický ústav SAV,  Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (186, 'Ústav matematických vied, Prírodovedecká fakulta UPJŠ, Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (187, 'Matematickofyzikální fakulta, Univerzita Karlova, Praha', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (188, 'School of Mathematics and Statistics, Carleton University, Ottawa, Canada', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (189, 'Katedra kvantiotatívnych metód a informačných systémov, Ekonomická fakulta, Univerzita Mateja Bela v Banskej Bystrici', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (190, 'Katedra fyziky, elektrotechniky a aplikopvanej mechaniky, Drevárska fakulta TU vo Zvolene', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (191, 'PF Katolícka univerzita v Ružomberku', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (192, 'Obchodná akadémia, F. Madvu 2, Prievidza', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (193, 'Katedra informatiky, Fakulta prírodných vied, Univerzita Mateja Bela, Banská Bystrica', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (194, 'FMFI, Univerzita Komenského, Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (195, 'Katedra analýzy, Fakulta matematiky, Univerzita v Białymstoku;', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (196, 'Szent István High School Budapest', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (197, 'Katedra matematiky a teoretickej informatiky, Fakulta elektrotechniky a informatiky Technickej univerzity v Košiciach', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (198, 'Dopravní fakulta Jana Pernera, Univerzita Pardubice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (199, 'Ústav matematických vied, Prírodovedecká fakulta Univerzity Pavla Jozefa Šafárika, Košice', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (200, 'Loránd Eötvös University, Physics Education Research Group, Budapest', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (201, 'Loránd Eötvös University, Department of Meteorology, Budapest', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (202, 'Žilinská univerzita v Žiline', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (203, 'Námestie Majstra Pavla 30,054 01 Levoča,', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (204, 'Matematický ústav SAV, Štefánikova 49, 814 73 Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (205, 'Ústav lekárskej fyziky, biofyziky, informatiky a telemedicíny LF UK v Bratislave', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (206, 'Katedra fyziky, matematiky a techniky, Fakulta humanitných a prírodných vied, Prešovskej univerzity v Prešove', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (207, '5 Katedra fyziky, matematiky a techniky, Fakulta humanitných a prírodných vied, Prešovskej univerzity v Prešove', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (208, '5 Katedra fyziky, matematiky a techniky, Fakulta humanitných a prírodných vied, Prešovskej univer- zity v Prešove,5 Katedra fyziky, matematiky a techniky, Fakulta humanitných a prírodných vied, Prešovskej univerzity v Prešove', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (209, 'Fyzikální ústav AV ČR, Praha,Česká republika', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (210, 'Department of Mathematics, Catholic University of America, Washington, D.C. 20064, U.S.A.', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (211, 'Katedra didaktiky matematiky, fyziky a informatiky, FMFI UK, Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (212, 'Přírodovědecká fakulta, Univerzita Palackého, Olomouc', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (213, 'Katedra didaktiky matematiky, fyziky a informatiky, Fakulta matematiky, fyziky a informatiky, Univerzita Komenského, Bratislava', NOW(), NOW());
INSERT INTO institutes (id, name, created_at, updated_at) VALUES (214, 'Katedra informatiky, PF KU v Ružomberku', NOW(), NOW());
